/*Change the <<Password>> to appropriate password, add tablespacename */

CREATE USER DATAADAPTER IDENTIFIED BY <<Password>>
/
GRANT CREATE SESSION TO DATAADAPTER
/
GRANT SELECT ON VLDS.NSC_STUDENT_RECORD TO DATAADAPTER
/
GRANT SELECT ON VLDS.STUDENT_COURSES TO DATAADAPTER
/
GRANT SELECT ON VLDS.STUDENT_DEMOGRAPHIC_LOG TO DATAADAPTER
/
GRANT SELECT ON VLDS.STUDENT_LVL_RECORD TO DATAADAPTER
/
GRANT SELECT ON VLDS.STUDENT_REC TO DATAADAPTER
/
GRANT SELECT ON VLDS.UNIQUE_STUDENTS TO DATAADAPTER
/
ALTER USER DATAADAPTER QUOTA UNLIMITED ON <<TableSpaceName>>
/
GRANT CREATE TABLE TO DATAADAPTER
