/*Replace <<TableSpaceName>> with TABLESPACE name*/

CREATE INDEX STUCOUR_INTID_ID_IDX ON VLDS.STUDENT_COURSES
(INTERNAL_ID) TABLESPACE <<TableSpaceName>>
/
CREATE INDEX SLR_INTID_IDX ON VLDS.STUDENT_LVL_RECORD
(INTERNAL_ID) TABLESPACE <<TableSpaceName>>
/
CREATE INDEX UNQSTU_INTID_IDX ON VLDS.UNIQUE_STUDENTS
(INTERNAL_ID) TABLESPACE <<TableSpaceName>>
/
CREATE INDEX STUREC_INTID_IDX ON VLDS.STUDENT_REC
(INTERNAL_ID) TABLESPACE <<TableSpaceName>>
/
CREATE INDEX NSCSTUREC_INTID_IDX ON VLDS.NSC_STUDENT_RECORD
(INTERNAL_ID) TABLESPACE <<TableSpaceName>>
/
