DROP TABLE [dbo].[TEST_DETAIL_1];
CREATE TABLE [dbo].[TEST_DETAIL_1](
	[INTERNAL_ID]  [varchar](50) NOT NULL,
	[MATH_SCORE]    INTEGER NULL,
	[READING_SCORE] INTEGER NULL,
	[WRITING_SCORE] INTEGER NULL,
    [YEAR]          INTEGER NULL
);

DROP TABLE [dbo].[TEST_DETAIL_2];
CREATE TABLE [dbo].[TEST_DETAIL_2](
	[INTERNAL_ID]  [varchar](50) NOT NULL,
	[RUDA_1] INTEGER NULL,
	[RUDA_2] FLOAT NULL,
    [YEAR]   INTEGER NULL
);