/*******************************************************************/
/** EXECUTE THIS SCRIPT IN SSMS WITH QUERY MENU -> SQLCMD MODE ON **/
/** (ON DEVELOPMENT MACHINES, THIS TAKES LESS THAN A MINUTE)      **/
/*******************************************************************/

/** CHANGE THE LOC VAR TO THE SCRIPT DIRECTORY**/
:SETVAR LOC "C:\Work\Tools\LocalExposureTestDb\TestSets\VERSION2\MSSQL\"

/** UNCOMMENT THE FOLLOWING TWO LINES TO LET THIS SCRIPT CREATE THE LEXICON DATABASE **/
/** INFRASTRUCTURE TEAM WILL MANUALLY CREATE THE VLDS_LEXICON DATABASE TO AVOID ERRORS EFFECTING THE MASTER DB **/
:r $(LOC)CREATE_EXPOSURE_DATABASE.sql
:r $(LOC)CREATE_DA_ROLE.sql
:r $(LOC)CREATE_EXPOSURE_INDICES.sql
:r $(LOC)CREATE_EXPOSURE_TABLES.sql

